import {service} from "./stuff-operations";

export const DELETE_STUFF_MEMBER_REQUESTED = 'DELETE_STUFF_MEMBER_REQUESTED'

export const DELETE_STUFF_MEMBER_LOADED = 'DELETE_STUFF_MEMBER_LOADED'

export const DELETE_STUFF_MEMBER_FAILED = 'DELETE_STUFF_MEMBER_FAILED'

export const CLOSE_STUFF_MODAL = 'CLOSE_STUFF_MODAL'

export const OPEN_STUFF_MODAL = 'OPEN_STUFF_MODAL'

export const ADD_POSITION = 'ADD_POSITION'

export const GET_POSITION = 'GET_POSITION'

export const DELETE_POSITION = 'DELETE_POSITION'

export const POSITION_FAILED = 'POSITION_FAILED'

export const POSITION_REQUESTED = 'POSITION_REQUESTED'

export const ADD_STUFF_MEMBER = 'ADD_STUFF_MEMBER'

export const FETCH_STUFF_LIST_REQUESTED = 'FETCH_STUFF_LIST_REQUESTED'

export const FETCH_STUFF_LIST_LOADED = 'FETCH_STUFF_LIST_LOADED'

export const FETCH_STUFF_LIST_FAILED = 'FETCH_STUFF_LIST_FAILED'

export const STUFF_PAGE_CHANGED = 'STUFF_PAGE_CHANGED'

export const PREVIOUS_STUFF_PAGE = 'PREVIOUS_STUFF_PAGE'

export const NEXT_STUFF_PAGE = 'NEXT_STUFF_PAGE'

export const UPDATE_STUFF_MEMBER_LOADED = 'UPDATE_STUFF_MEMBER_LOADED'

export const UPDATE_STUFF_MEMBER_REQUESTED = 'UPDATE_STUFF_MEMBER_REQUESTED'

export const UPDATE_STUFF_MEMBER_FAILED = 'UPDATE_STUFF_MEMBER_FAILED'

